export default [
        {
          id: 261,
          createTime: "2022-07-14 15:19:27",
          updateTime: "",
          searchValue: "",
          customerName: "四川天呈优选电子商务有限公司",
          contractName: "0714销售合同01",
          contractNum: "aa0714-01",
          projectName: "四川天呈0714项目一",
          ownLinkman: "",
          ownLinkmanMobile: "",
          bankCard: "",
          contactName: "",
          contactMobile: "",
          startTime: "2022-07-14 00:00:00",
          endTime: "2022-10-08 23:59:59",
          effectiveRecord: [
            {
              createTime: "",
              updateTime: "",
              startTime: "",
              endTime: "",
              efeffectiveFile: "",
              remark: "",
              operatorName: "",
            },
          ],
          effectiveStartTime: "2022-07-14 00:00:00",
          effectiveEndTime: "2022-10-08 23:59:59",
          payType: "1",
          createUserName: "",
          contractStatus: 1,
          creditApplyStatus: -1,
          creditApplyStr: "",
          productAdjustStatus: 0,
          contractContent: "",
          remark: "",
          contractFile: "",
          fileUrlPrefix: "",
          adjustDingTalkContent: "",
          creditDingTalkContent: "",
          contractProductList: [],
          signingCompanyName: "",
          releaseStatus: {},
          cashOutStatus: {},
          planFreePay: false,
          appendix: [],
          businessNotifier: "",
          ids: [],
          payTypeStr: "线下支付",
          validityTimeStr: "2022-07-14 至 2022-10-08",
        },
        {
          id: 255,
          createTime: "2022-07-13 15:27:28",
          updateTime: "",
          searchValue: "",
          customerName: "四川天呈优选电子商务有限公司",
          contractName: "0713销售合同01",
          contractNum: "aa0713-01",
          projectName: "四川天呈0713项目一",
          ownLinkman: "",
          ownLinkmanMobile: "",
          bankCard: "",
          contactName: "",
          contactMobile: "",
          startTime: "2022-07-13 00:00:00",
          endTime: "2022-09-30 23:59:59",
          effectiveRecord: [
            {
              createTime: "",
              updateTime: "",
              startTime: "",
              endTime: "",
              efeffectiveFile: "",
              remark: "",
              operatorName: "",
            },
          ],
          effectiveStartTime: "2022-07-13 00:00:00",
          effectiveEndTime: "2022-09-30 23:59:59",
          creditAmount: 20000,
          payType: "3,2,1",
          createUserName: "",
          contractStatus: 1,
          creditApplyStatus: 0,
          creditApplyStr: "审批通过",
          productAdjustStatus: -1,
          contractContent: "",
          remark: "",
          billTime: 60,
          contractFile: "",
          fileUrlPrefix: "",
          adjustDingTalkContent: "",
          creditDingTalkContent: "",
          contractProductList: [],
          signingCompanyName: "",
          releaseStatus: {},
          cashOutStatus: {},
          residueAmount: 20000,
          planFreePay: false,
          appendix: [],
          businessNotifier: "",
          ids: [],
          payTypeStr: "在线支付,授信支付,线下支付",
          validityTimeStr: "2022-07-13 至 2022-09-30",
        },
      {
          id: 261,
          createTime: "2022-07-14 15:19:27",
          updateTime: "",
          searchValue: "",
          customerName: "四川天呈优选电子商务有限公司",
          contractName: "0714销售合同01",
          contractNum: "aa0714-01",
          projectName: "四川天呈0714项目一",
          ownLinkman: "",
          ownLinkmanMobile: "",
          bankCard: "",
          contactName: "",
          contactMobile: "",
          startTime: "2022-07-14 00:00:00",
          endTime: "2022-10-08 23:59:59",
          effectiveRecord: [
            {
              createTime: "",
              updateTime: "",
              startTime: "",
              endTime: "",
              efeffectiveFile: "",
              remark: "",
              operatorName: "",
            },
          ],
          effectiveStartTime: "2022-07-14 00:00:00",
          effectiveEndTime: "2022-10-08 23:59:59",
          payType: "1",
          createUserName: "",
          contractStatus: 1,
          creditApplyStatus: -1,
          creditApplyStr: "",
          productAdjustStatus: 0,
          contractContent: "",
          remark: "",
          contractFile: "",
          fileUrlPrefix: "",
          adjustDingTalkContent: "",
          creditDingTalkContent: "",
          contractProductList: [],
          signingCompanyName: "",
          releaseStatus: {},
          cashOutStatus: {},
          planFreePay: false,
          appendix: [],
          businessNotifier: "",
          ids: [],
          payTypeStr: "线下支付",
          validityTimeStr: "2022-07-14 至 2022-10-08",
        },
        {
          id: 255,
          createTime: "2022-07-13 15:27:28",
          updateTime: "",
          searchValue: "",
          customerName: "四川天呈优选电子商务有限公司",
          contractName: "0713销售合同01",
          contractNum: "aa0713-01",
          projectName: "四川天呈0713项目一",
          ownLinkman: "",
          ownLinkmanMobile: "",
          bankCard: "",
          contactName: "",
          contactMobile: "",
          startTime: "2022-07-13 00:00:00",
          endTime: "2022-09-30 23:59:59",
          effectiveRecord: [
            {
              createTime: "",
              updateTime: "",
              startTime: "",
              endTime: "",
              efeffectiveFile: "",
              remark: "",
              operatorName: "",
            },
          ],
          effectiveStartTime: "2022-07-13 00:00:00",
          effectiveEndTime: "2022-09-30 23:59:59",
          creditAmount: 20000,
          payType: "3,2,1",
          createUserName: "",
          contractStatus: 1,
          creditApplyStatus: 0,
          creditApplyStr: "审批通过",
          productAdjustStatus: -1,
          contractContent: "",
          remark: "",
          billTime: 60,
          contractFile: "",
          fileUrlPrefix: "",
          adjustDingTalkContent: "",
          creditDingTalkContent: "",
          contractProductList: [],
          signingCompanyName: "",
          releaseStatus: {},
          cashOutStatus: {},
          residueAmount: 20000,
          planFreePay: false,
          appendix: [],
          businessNotifier: "",
          ids: [],
          payTypeStr: "在线支付,授信支付,线下支付",
          validityTimeStr: "2022-07-13 至 2022-09-30",
        },
      {
          id: 261,
          createTime: "2022-07-14 15:19:27",
          updateTime: "",
          searchValue: "",
          customerName: "四川天呈优选电子商务有限公司",
          contractName: "0714销售合同01",
          contractNum: "aa0714-01",
          projectName: "四川天呈0714项目一",
          ownLinkman: "",
          ownLinkmanMobile: "",
          bankCard: "",
          contactName: "",
          contactMobile: "",
          startTime: "2022-07-14 00:00:00",
          endTime: "2022-10-08 23:59:59",
          effectiveRecord: [
            {
              createTime: "",
              updateTime: "",
              startTime: "",
              endTime: "",
              efeffectiveFile: "",
              remark: "",
              operatorName: "",
            },
          ],
          effectiveStartTime: "2022-07-14 00:00:00",
          effectiveEndTime: "2022-10-08 23:59:59",
          payType: "1",
          createUserName: "",
          contractStatus: 1,
          creditApplyStatus: -1,
          creditApplyStr: "",
          productAdjustStatus: 0,
          contractContent: "",
          remark: "",
          contractFile: "",
          fileUrlPrefix: "",
          adjustDingTalkContent: "",
          creditDingTalkContent: "",
          contractProductList: [],
          signingCompanyName: "",
          releaseStatus: {},
          cashOutStatus: {},
          planFreePay: false,
          appendix: [],
          businessNotifier: "",
          ids: [],
          payTypeStr: "线下支付",
          validityTimeStr: "2022-07-14 至 2022-10-08",
        },
        {
          id: 255,
          createTime: "2022-07-13 15:27:28",
          updateTime: "",
          searchValue: "",
          customerName: "四川天呈优选电子商务有限公司",
          contractName: "0713销售合同01",
          contractNum: "aa0713-01",
          projectName: "四川天呈0713项目一",
          ownLinkman: "",
          ownLinkmanMobile: "",
          bankCard: "",
          contactName: "",
          contactMobile: "",
          startTime: "2022-07-13 00:00:00",
          endTime: "2022-09-30 23:59:59",
          effectiveRecord: [
            {
              createTime: "",
              updateTime: "",
              startTime: "",
              endTime: "",
              efeffectiveFile: "",
              remark: "",
              operatorName: "",
            },
          ],
          effectiveStartTime: "2022-07-13 00:00:00",
          effectiveEndTime: "2022-09-30 23:59:59",
          creditAmount: 20000,
          payType: "3,2,1",
          createUserName: "",
          contractStatus: 1,
          creditApplyStatus: 0,
          creditApplyStr: "审批通过",
          productAdjustStatus: -1,
          contractContent: "",
          remark: "",
          billTime: 60,
          contractFile: "",
          fileUrlPrefix: "",
          adjustDingTalkContent: "",
          creditDingTalkContent: "",
          contractProductList: [],
          signingCompanyName: "",
          releaseStatus: {},
          cashOutStatus: {},
          residueAmount: 20000,
          planFreePay: false,
          appendix: [],
          businessNotifier: "",
          ids: [],
          payTypeStr: "在线支付,授信支付,线下支付",
          validityTimeStr: "2022-07-13 至 2022-09-30",
        },
      
	  ]